version: '3.8'
services:
  mongodb:
    image: mongo:5.0.26-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: your_secure_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nextjs:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    command: >
      sh -c "npx prisma generate &&
             npx prisma db push &&
             npm run dev"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: your_secure_password
      ME_CONFIG_MONGODB_URL: mongodb://admin:your_secure_password@mongodb:27017/

volumes:
  mongodb_data:
