# permlink
# https://plantuml.github.io/plantuml-core/raw.html?vLHBRzf04BxlhnXnWKW46sC7uqCFQQ8g5n91UwfwsFMEmOsnqQwTj4N-xvtTDH12LBLIRfLyMC_ZcyStCvcgoXekFq1c7uofigeHgYTKJiIsNF6DXWHs362hgk-OrdTogFbcMo0zG3TYUVn9UNadMSkmb1QACPRjO_1jJZW694MjOR3xIxZsWZ7ZIn1I44A9pr1p_GZ7t60q6a7B6EaFWOn9iYD5Ur8MAPdrDWNbCe7-rNGo2IOo47uwJiCn1fcFGHZE-aEom1-Oait3ulxZxN9fHIwiwyYX9nPd78iu3AzuE9wcOX87wJGUes-T05oDdHsAgJYncyoYlLqZZgPHB34GF9pm8E9P5Cs2MPRvuTxKziT21Zpq8uoZK0YU-I8MaH_5GP_CMcDRL2jgN5CKjW1KAPQKic_-TCthXihfBxxCvtVpJnPR2esAsaNYTLrl4y_xLLKTSwDyWq-N6rIZJ2Mn7u-zfx7NFo6zeyjHxwYWiNWz2gef3wgN1A-mNb9b0rVUnGchLbPcrHcdHc4v8SQfWEL-ZlOy6JtvVoNrDzELj_BjGY1NwHe4JnzNgcfA2LphAirvZV8ih07le7jPNY0qgkY1QQ7nFnDgbKBIs_9wxVwbDlqv24ZY6k8ui32K3IhA5k3bLdKPRt_Mwye4xxWPx4mo3mGtj0cubyMy6SBDzH2kBPxPgVMn4WTZygCGSBjOt2-wkO0yWqskTLwke5A4ATtyOurAcuGi2kloS3rCuE5--Hay4zRRkOBQFTx0mRyLdyh0GkE-5lOswc4_lDtXIVWUbv8EGRxXgmC2IkBvNK3-gS2R-_ajNBnsKKXKxofXhWKyv_NQXT77EEshuQBH9QSM6eqPhIuyhx64iZ9BGgBJTKh0t3Hxs5mU9nlrKdwwdUSN_pyzZZrHSFfwVpYGXjTtk8w_0G00

@startuml Process


front -> front 

rnote over front
params : {
  projectId,sampleId, subSampleId, scanId
}
endrnote


front -> api :  process ({projectId,sampleId, subSampleId, scanId})

api -> db : new task params : { ... }

db -> api : task:{...}

rnote over api
task {
  id: '673323d2b0c1c41e2f0e2449',
  exec: 'PROCESS',
  params: {
    project: '6718b8446a417cb382c781e0',
    sample: '6718eb7b6a417cb382c78395',
    subsample: '658de2ba43a25af55929ff04',
    scanId: '672a405e854bbaf0b8b50582'
  },
  log: null,
  percent: 0,
  status: 'RUNNING',
  dbserver: 'http://zooprocess.imev-mer.fr:8081/v1/'
}
endrnote

api -> front : taskId

front -> api : run taskId

api -> db : getScan(scanId)
db -> api : scanInfo

rnote over api
scan: {
 ...
  SubSample: {
    scan : [...]
  }
}
endrnote

api -> api : search background associated

rnote over api
{
  scan : "file url" ,
  back: "file url" ,
  src :"path" ,
  dst : "path" ,

  taskId,
  db,
  bearer
}
  
endrnote


api -> python : process({scanPath, backPath, taskID, DB, Bearer})

hnote over python
  send ERROR status if missing or bad parameters
endhnote
python -> api: POST /task/{taskId} status ( ERROR)

hnote over python : else process

python -> api: POST /subsample/{subsampleId}/add { image processed }
python -> api: POST /subsample/{subsampleId}/add { image processed }

python -> api: POST /task/{taskId} status ( DONE )
python -> api: ret :{object with images processed}
rnote over api: {ret} usefull when no db use

front -> api: ask task status
api -> db : task status


api -> front
rnote over front
task {
  id: '673323d2b0c1c41e2f0e2449',
  exec: 'PROCESS',
  params: {
    project: '6718b8446a417cb382c781e0',
    sample: '6718eb7b6a417cb382c78395',
    subsample: '658de2ba43a25af55929ff04',
    scanId: '672a405e854bbaf0b8b50582'
  },
  log: "blabla",
  percent: 0,
  status: 'DONE',
  dbserver: 'http://zooprocess.imev-mer.fr:8081/v1/'
}
endrnote

@enduml


