@startuml
(*)  --> "Preview" as preview
    if "preview OK" then
      --> [30s]  "Scan" as scan
      if "preview OK" then
        --> "Process"
        --> "Check Segmentation"
        --> "Check Multiple"

       if "check" then 
         --> "OK" 
        --> "Decoupe multiple"
         --> (*)
       else 
          if "fraction" then
           --> [ok] preview
          else
            -> [nok] "Fill fraction"
            --> "purge old"
            --> preview
          endif
       endif
      else 
        -> [false] "move organism " 
        --> scan
      endif
    else 
       -> [false] "move organism" 
       --> preview
    endif

@enduml


