# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    # image: mongo:5.0.22-focal
    image: prismagraphql/mongo-single-replica:5.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
      # - ./conf:/etc/mongodb
      - ./log:/var/log/mongodb
      # - ./keyfile:/data/keyfile

    ports:
      - 27017:27017
    # command:
    #   - '--auth'
    #   - '-f'
    #   - '/etc/mongodb/mongodb.conf'
    # entrypoint:
    #         - bash
    #         - -c
    #         - |
    #             chmod 400 /data/replica.key
    #             chown 999:999 /data/replica.key
    #             exec docker-entrypoint.sh $$@     
    # command: "mongod --bind_ip_all --replSet replicaSet01 --keyFile /data/replica.key"

  mongo-express:
    image: mongo-express:1.0.0-20-alpine3.18
    restart: always
    ports:
      - 18081:8081
    environment:
      # old version of mongo-express
      # - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      # - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      # new version of mongo-express
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/db
    # volumes:
    #   - ./express:/node_modules/mongo-express